package org.mouji.common.info;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <h5>Service Request</h5>
 * 
 * <p>
 * ServiceRequest object contains the following fields:
 * </p>
 * <ul style="list-style-type: circle; margin-left: 3em;">
 * <li><strong>service*: </strong>Instance of ServiceInfo object</li>
 * <li><strong>env*: </strong>StubType object instance</li>
 * <li><strong>rid*: </strong>contains the request id generated for the request.
 * request id can be used by the client to identify responses in asynchronous or
 * batch mode.</li>
 * <li><strong>args*: </strong> an array of SerializedObject instanc</li>
 * </ul>
 * <br/>
 * 
 * @author Salim
 *
 */
public class ServiceRequest {

	/**
	 * service infomrmation
	 */
	private ServiceInfo<?> service;

	/**
	 * client enviroment info
	 */
	private StubEnvInfo env;

	/**
	 * request id generated by client
	 */
	private long requestId;

	/**
	 * list of argument objects
	 */
	private SerializedObject<?>[] args;

	/**
	 * dummy constructor for serialization
	 */
	public ServiceRequest() {
	}

	public ServiceRequest(ServiceInfo<?> service, StubEnvInfo env, long requestId, SerializedObject<?>[] args) {
		this.service = service;
		this.env = env;
		this.requestId = requestId;
		this.args = args;
	}

	public SerializedObject<?>[] getArgs() {
		return args;
	}

	public void setArgs(SerializedObject<?>[] args) {
		this.args = args;
	}

	@JsonProperty("rid")
	public long getRequestId() {
		return requestId;
	}

	public void setRequestId(long requestId) {
		this.requestId = requestId;
	}

	public StubEnvInfo getEnv() {
		return env;
	}

	public void setEnv(StubEnvInfo env) {
		this.env = env;
	}

	public ServiceInfo<?> getService() {
		return service;
	}

	public void setService(ServiceInfo<?> service) {
		this.service = service;
	}

	public static ServiceRequest create(ServiceInfo<?> service, long id, Object[] args) {
		SerializedObject<?>[] serializedArgs = new SerializedObject[args.length];
		for (int i = 0; i < serializedArgs.length; i++) {
			serializedArgs[i] = new SerializedObject<>(args[i]);
		}

		ServiceRequest request = new ServiceRequest(service, StubEnvInfo.currentEnvInfo(), id, serializedArgs);
		return request;
	}

	@Override
	public String toString() {
		return "{ServiceRequest  service: " + service + " ,  requestId: " + requestId + " ,  env: " + env + " ,  args: "
				+ args + "}";
	}

}
